### ISSUE TITLE
capstoneFunctions.py: could not broadcast input array from shape (2) into shape (3)

### ISSUE THREAD

**Issue by amuhamm** [amackillop/SpeechBuddy1#2]
File "C:\Programming\SpeechBuddy1\api\capstoneModules\capstoneFunctions.py", line 1072, in parabolicInterpolation
    ordinates[i-1] = cum_diff_matrix[i, tau-1:tau+2]
ValueError: could not broadcast input array from shape (2) into shape (3)
[17/Mar/2018 01:30:48] "POST /api/google/ HTTP/1.1" 500 16898

![image](https://user-images.githubusercontent.com/14007354/37552013-ee332302-2982-11e8-8841-f24687d02c67.png)

**Comment by amackillop** [comment]
I can't recreate this now. But if it keeps happening check to make sure the original file is deleted 
![image](https://user-images.githubusercontent.com/33668612/37555346-5ca69876-29bc-11e8-8ae6-882a833b44fd.png)

EDIT: This happens when the audio signal is too short after trimming and compression. Parabolic interpolation will throw away the end samples of the compressed speech signal. If the signal is only 4 timesteps and the ends get thrown away then python is left with only two samples to use in a parabolic interpolation that requires three points. I have added an exception to handle this error.
